service: sls-demo

provider:
  name: aws
  runtime: nodejs12.x

region: ap-southeast-2

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello
  job:
    handler: src/jobs/handler.handler
  listJobs:
    handler: src/jobs/list.handler
    events: 
      - http:
          method: GET
          path: /jobs
  createJobs:
    handler: src/jobs/create.handler
    events: 
      - http:
          method: POST
          path: /jobs
  fetchJob:
    handler: src/jobs/findOne.handler
    events:
      - http:
          method: GET
          path: /jobs/{id}
          request:
            parametres:
              id: true
        
      